---
title: Standards for Mapping Semantic Artifacts in NFDI
subtitle: NFDI working group Ontology harmonization and mapping
authors:
  - name: Jakob Voß
    affiliation: Verbundzentrale des GBV (VZG)
    orcid: 0000-0002-7613-4123 
  - name: Naouel Karam
    affiliation: Frauenhofer FOKUS
  - name: Mark Doerr
    affiliation: Institute of Biochemistry, University Greifswald
  - name: Alexander Wolodkin
    affiliation: Senckenberg Gesellschaft für Naturforschung 
  - name: Josh Moore
    affiliation: GerBI-GMB
bibliography: references.bib
---

# Ojective

The objective of this docment is described in @charta2022 as following:

> Assessment of standards (i.e. formal, accessible, shared and broadly applicable language for knowledge representation) for the creation of mappings (e.g., SSSOM, OAEI), the formal documentation of mappings and their metadata in collaboration with the Terminology Services WG, as well as their (re-)evaluation and publication. 

This may also include tools, procedures, frameworks and recommendations for the creation, documentation, validation and publishing of mappings.

# Background

Different domains and projects use different semantic Artifacts (SA) subsuming all kinds of formal ontologies, terminologies, vocabularies and similar knowledge organization systems in their research data.

Mappings, also known as crosswalks, concordances, alignments... can help for data integration and enrichement by bridging the gap between different data models and vocabularies. In this document we use the following words:

- a **mapping** is ...
- a ... is a set of mappings

# Review

## Non-Standards but reality

- Visual graphs (mostly with pen and paper): useful for thinking but not formal
- Source code of applications that apply transformations: better than a standard without implementation but not scalable
- Spreadsheets: the plague but unavoidable and handy

## Standards

In no particular order:

- [LinkML-map](https://linkml.io/linkml-map/)
- [JSKOS mappings](https://gbv.github.io/jskos/#concept-mappings) and [Concordances](https://gbv.github.io/jskos/#concordances)
- [SKOS mapping properties](https://www.w3.org/TR/skos-reference/#mapping)
- RDFS and OWL properties
- ontology mapping & alignment (OAEI)
- Simple Standard for Sharing Ontological Mappings (SSSOM)
- RML
- ...

# Instructions and recommendations

This document may eventually contain recommendations on

- creation of mappings
- validation of mappings
- documentation of mappings
- publication of mappings
- mapping tools
- mapping registries

To get there we will

- Find instructions and have specialist discussions on  from the field of computer science.
- Refer to existing guidelines
- Assess and discuss how to use existing standards in NFDI
- ...

## Tools

Not main topic of this document but should be mentioned.

- Cocoda
- "There are many tools and frameworks that can be used to assist with ontology matching and alignment, such as Alignment API, AgreementMaker, LogMap, AML, and OntoComP."^[<https://www.linkedin.com/advice/0/what-best-practices-tools-ontology-matching?lang=en>]
- ...

Many tools have been proposed in context of OAEI but they rarely become more than a short-lived research demo.

~~~{.ttl}
# Just an example how to include RDF/Turtle in this document
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

<A> skos:exactMatch <B> .
~~~
